# Generated by Django 4.1.6 on 2023-03-23 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjagoApplication', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DjagoApplication',
            new_name='Userinfo',
        ),
    ]
